/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.30 from the
 * contents of Mytest.xs. Do not edit this file, edit Mytest.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Mytest.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "sys/mount.h"
#include "ppport.h"


#line 18 "Mytest.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 162 "Mytest.c"

XS_EUPXS(XS_Mytest_hello); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Mytest_hello)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 12 "Mytest.xs"
	    printf("Hello, world!\n");
#line 173 "Mytest.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Mytest_is_even); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Mytest_is_even)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "input");
    {
	int	input = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;
#line 18 "Mytest.xs"
        RETVAL = (input % 2 == 0);
#line 192 "Mytest.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Mytest_round); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Mytest_round)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "arg");
    {
	double	arg = (double)SvNV(ST(0))
;
#line 25 "Mytest.xs"
    		if (arg > 0.0) {
    			arg = floor(arg + 0.5);
    		} else if (arg < 0.0) {
    			arg = ceil(arg - 0.5);
    		} else {
    			arg = 0.0;
    		}
#line 216 "Mytest.c"
	sv_setnv(ST(0), (double)arg);
	SvSETMAGIC(ST(0));
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Mytest_statfs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Mytest_statfs)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	path = (char *)SvPV_nolen(ST(0))
;
#line 38 "Mytest.xs"
            int i;
            struct statfs buf;
#line 238 "Mytest.c"
#line 41 "Mytest.xs"
    		i = statfs(path, &buf);
    		if (i == 0) {
    			XPUSHs(sv_2mortal(newSVnv(buf.f_bavail)));
    			XPUSHs(sv_2mortal(newSVnv(buf.f_bfree)));
    			XPUSHs(sv_2mortal(newSVnv(buf.f_blocks)));
    			XPUSHs(sv_2mortal(newSVnv(buf.f_bsize)));
    			XPUSHs(sv_2mortal(newSVnv(buf.f_ffree)));
    			XPUSHs(sv_2mortal(newSVnv(buf.f_files)));
    			XPUSHs(sv_2mortal(newSVnv(buf.f_type)));
    		} else {
    			XPUSHs(sv_2mortal(newSVnv(errno)));
    		}
#line 252 "Mytest.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Mytest_multi_statfs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Mytest_multi_statfs)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "paths");
    {
	SV *	paths = ST(0)
;
	SV *	RETVAL;
#line 57 "Mytest.xs"
        	    AV * results;
        	    SSize_t numpaths = 0, n;
        	    int i;
        	    struct statfs buf;
        	    SvGETMAGIC(paths);
        	    if ((!SvROK(paths))
        		|| (SvTYPE(SvRV(paths)) != SVt_PVAV)
        		|| ((numpaths = av_top_index((AV *)SvRV(paths))) < 0))
        	    {
        		XSRETURN_UNDEF;
        	    }
        	    results = (AV *)sv_2mortal((SV *)newAV());
#line 282 "Mytest.c"
#line 70 "Mytest.xs"
        	    for (n = 0; n <= numpaths; n++) {
            		HV * rh;
            		STRLEN l;
            		char * fn = SvPV(*av_fetch((AV *)SvRV(paths), n, 0), l);
            		i = statfs(fn, &buf);
            		if (i != 0) {
            		    av_push(results, newSVnv(errno));
            		    continue;
            		}
            		rh = (HV *)sv_2mortal((SV *)newHV());
            		hv_store(rh, "f_bavail", 8, newSVnv(buf.f_bavail), 0);
            		hv_store(rh, "f_bfree",  7, newSVnv(buf.f_bfree),  0);
            		hv_store(rh, "f_blocks", 8, newSVnv(buf.f_blocks), 0);
            		hv_store(rh, "f_bsize",  7, newSVnv(buf.f_bsize),  0);
            		hv_store(rh, "f_ffree",  7, newSVnv(buf.f_ffree),  0);
            		hv_store(rh, "f_files",  7, newSVnv(buf.f_files),  0);
            		hv_store(rh, "f_type",   6, newSVnv(buf.f_type),   0);
            		av_push(results, newRV((SV *)rh));
        	    }
        	    RETVAL = newRV((SV *)results);
#line 304 "Mytest.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Mytest); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Mytest)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Mytest::hello", XS_Mytest_hello);
        newXS_deffile("Mytest::is_even", XS_Mytest_is_even);
        newXS_deffile("Mytest::round", XS_Mytest_round);
        newXS_deffile("Mytest::statfs", XS_Mytest_statfs);
        newXS_deffile("Mytest::multi_statfs", XS_Mytest_multi_statfs);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

